#!/usr/bin/env bash
# Transfers file from client to the server
if [ "$#" -lt 4 ]; then
	echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY";
	exit 1;
else
	scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3@$2":~/
fi
