#!/usr/bin/env bash
# /redirect_me direct to another page permanently
apt-get update -y
apt-get install nginx -y
ufw allow "Nginx HTTP"
echo "Hello World!" | tee /var/www/html/index.html > /dev/null 2>&1
sed -i '/listen 80 default_server/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4/ permanent;' /etc/nginx/sites-available/default
service nginx start
