#!/usr/bin/env bash
# Configure Nginx so that its HTTP response contains
# a custom header
#
balancer="\
frontend haproxy_balancer
    bind *:80
    mode http
    default_backend webservers
    
backend webservers
    balance roundrobin
    server 26071-web-01 100.26.50.181:80 check
    server 26071-web-02 18.207.141.60:80 check
"
# Update packages
apt-get -y update
apt-get -y upgrade

# Add HAProxy PPA
apt-get install -y --no-install-recomends software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-2.8
apt-get -y update

# Install HAProxy
apt-get -y install haproxy=2.8.\*
cp -a /etc/haproxy/haproxy.cfg{,.orig}
echo "$balancer" >> /etc/haproxy/haproxy.cfg
service haproxy restart
