#!/usr/bin/env bash
# This bash script creates a file and store its pid in the file
# but on receiving SIGQUIT or SIQTERM signal it delets the file then exits
file="/var/run/"
trap 'echo "Y U no love me?!"; exit 255' SIGINT


while :
do
	echo "To inifinity and beyond"
	sleep 2
done
