#!/usr/bin/env bash
# This bash script creates a file and store its pid in the file
# but on receiving SIGQUIT or SIQTERM signal it delets the file then exits
# shellcheck disable=SC2005
trap 'echo "Y U no love me?!"' SIGINT 
cleanup(){
	echo "I hate the kill command"
	rm -f "/var/run/myscript.pid" 
	exit
}
trap 'cleanup' SIGTERM SIGQUIT ERR
echo "$(pgrep -f "$0")" > "/var/run/myscript.pid"
while :
do
	echo "To inifinity and beyond"
	sleep 2
done
