#!/usr/bin/env bash
# This bash script displays indefinitely and displays I am invincible
# when receiving a SIGTERM signal
trap 'echo "I am invincible!!!"' SIGTERM
while :
do
	echo "To infinity and beyond"
	sleep 2
done
