#!/usr/bin/env bash
# bash script that display username, user id, and home directory
# shellcheck disable=SC2034
while IFS=: read -r f1 f2 f3 f4 f5 f6 f7
do
	#echo "$(cut -d: -f1,3,6)" # not printing the first line
	echo "$f1:$f3:$f6" # prints from the first line
done < "/etc/passwd"
#awk -F: '{print $1":"$3":"$6}' "/etc/passwd" # awk solution
