#!/usr/bin/env bash
# This bash script displays "Best School" 10 times, but "Hi" after
# 9th line.
((n=0))
while [ $n -lt 10 ]
do
	if ((n == 9))
	then
		echo "Hi"
	fi
	echo "Best School"
	((n+=1))
done
