#!/usr/bin/env bash

# check if the number of arguments is corrent
if [ "$#" -lt 4 ]; then
	echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY";
	exit 1;
fi
# Disable strict key checking and sent the file using send copy
scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3" "$2": ~/
