#!usr/bin/env bash
# A bash script that uses ssh to connect to a my server

# set variables
private_key=~/.ssh.school
user=ubuntu
server_ip=100.26.50.181

# Connect using ssh with single-character flags
ssh -i "$private_key" "$user"@"server_ip"
