#!/usr/bin/env bash
# Creates rsa Key pair

# Set varibles
private_key_name="school"
key_bits=4096
passphrase="betty"
key_type="rsa"

# Create rsa key pair with passphrase
ssh-keygen -t "$key_type" -b "$key_bits" -f "$private_key_name" -N "$passphrase"

# echo "RSA key pair created successfully."
# echo "Private key: $private_key_name"
# echo "Public key: $private_key_name.pub"
